version: '3'

services:
  api:
    build: ./
    restart: unless-stopped
    command: 'npm run tsc:watch'
    volumes:
      - ./dist:/app/dist
      - ./node_modules:/app/node_modules
      - ./src/:/app/src/
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json
    ports:
      - 9000:9000
    environment:
      - PORT=9000
      - APP_SECRET=${APP_SECRET}
    links:
      - pgsql
    depends_on:
      - pgsql

  pgsql:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: docker
      POSTGRES_DB: docker
    volumes:
      - postgres-data2:/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - pgsql

volumes:
  mongo-data:
  postgres-data2:
